version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:13.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  app:
    container_name: go_app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: